// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contacts.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package start;

@kotlin.jvm.JvmName("-initializepeopleInfo")
public inline fun peopleInfo(block: start.PeopleInfoKt.Dsl.() -> kotlin.Unit): start.PeopleInfo =
  start.PeopleInfoKt.Dsl._create(start.PeopleInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `start.PeopleInfo`
 */
public object PeopleInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: start.PeopleInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: start.PeopleInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): start.PeopleInfo = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `int32 age = 2;`
     */
    public var age: kotlin.Int
      @JvmName("getAge")
      get() = _builder.age
      @JvmName("setAge")
      set(value) {
        _builder.age = value
      }
    /**
     * `int32 age = 2;`
     */
    public fun clearAge() {
      _builder.clearAge()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun start.PeopleInfo.copy(block: `start`.PeopleInfoKt.Dsl.() -> kotlin.Unit): start.PeopleInfo =
  `start`.PeopleInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

